name: Release PDF/EPUB

on:
  push:
    tags:
      - "w*"

jobs:
  release:
    name: Release epub
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get the short tag
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Get the tag commit message
        id: tcm
        run: |
          VERSION="${{ steps.tag.outputs.VERSION }}"
          COMMIT_MSG=$(git tag -l --format='%(contents:subject)' "$VERSION")
          echo "COMMIT_MSG=$COMMIT_MSG" >> "$GITHUB_ENV"

      - name: Create the epub
        run: bash ./epub.sh

      - name: Create a new release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.VERSION }}
          prerelease: false
          draft: false
          body: ${{ env.COMMIT_MSG }}
          files: |
            arts.epub
            arts.pdf
